sudo: required

services:
  - docker

before_script:
  - docker pull esrice/rustbuilder:latest

script:
  - docker run -v "$(pwd)":/home/ubuntu/src esrice/rustbuilder /root/.cargo/bin/cargo build --target x86_64-unknown-linux-musl --release

deploy:
  provider: releases
  file:
    - target/x86_64-unknown-linux-musl/release/classify_by_alignment
    - target/x86_64-unknown-linux-musl/release/classify_by_kmers
    - find-unique-kmers
  on:
    repo: esrice/trio_binning
    tags: true
  api_key:
    secure: UBoPR0vhTayeBMsxIqp0pnYi5aoBkwBPL14ks9grTM+6OHTBtm7dGLdHmP9+ycF/UfQ70RERoo0YHLC0gHdYeYlUyJ2ypmqCX+vG+yjX9CQZz9ALmyAuQ9JupEYkc4KxYmxe9xbPNS4af95EjJ+wtaCGrtFrHdyRX3OxaCu2sj+ih7B0Y0Nie9OAqja+hoXoxCYF5UVOJ+f0RmxzWoTZGnx8kJR4OVrXXvcwjIxhgiUWXY3nr1YD5MFT8bvGhXWNPTahPWWC5ZvCEIUkl1/rCQdcTP3u7CJHd6COMtO1XmqtZ18FYrM76FChmqhNPEXOmAd7RbK4ji0bD3bCntzOBoSOLoPoPM+D2R+YbyjL8AQjHwin7ee/cjAePN2/WRqsyINxnYyMjYmVS8122JummLnNAPKd3fPFlcsYPwK1mBdcpULcVJogwNe+fbJIwImnTKgwDER2bmpSIfQTvC8rjxc+4z4k7Wi8oS9geyBtt8PSbLjKsG/q2uGMxF+o/6O5Ul/udSmCMSpQBgR9wMo44dfjjxMCO7gwGTd7mjs4Ky9XQ0fuJudlpyKh+lKp+aLaPbBEGwefh61Kk2VNCjZ+0B+1CNMgrLKX8inS2ctFzyNOVy4iYbjc5R2eSFkkD1J2rv40zpXKWnvwRvYfSUgt1EuXIAtE7XPDd55hd6sKqQo=
