language: rust

rust:
    - stable

sudo: required

services:
  - docker

before_script:
  - docker pull esrice/rustbuilder

script:
  - docker run -v "$(pwd)":/home/ubuntu/src esrice/rustbuilder \
        cargo build --target x86_64-unknown-linux-musl
